In [1]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv('cleaned_data_Allstores_dataset1.csv')
df.head()

,Unnamed: 0,Name,NameAr,LocalizedName,BusinessType,OtherTypeName,IsPopularBusiness,TotalReviews,Rating,Id,ActiveStatus,OwnerAllowStatus,CertificationStatus
0,1500,VIGOIR ARABIA,فيجور العربية,فيجور العربية,إلكترونيات,NaN,False,13,1.85,113480,0,1,1
1,1501,Riashapp,رياش اب,رياش اب,المنزل,NaN,False,12,1.83,79729,0,1,1
2,1502,Mohammed Jawad BuKhamseen for home appliances,مؤسسة محمد جواد صالح بوخمسين,مؤسسة محمد جواد صالح بوخمسين,إلكترونيات,NaN,False,10,1.80,60202,0,1,1
3,1515,Key Card,كي كارد,كي كارد,إلكترونيات,منتجات رقمية,False,11,1.73,203165,0,1,1
4,1516,Danube Online,الدانوب أونلاين,الدانوب أونلاين,خدمات الأعمال,NaN,False,15,1.67,91371,0,1,1

In [22]:
df1 = pd.read_csv('Labeled_review.csv')
df1.head()

,Unnamed: 0,BusinessId,review_id,rating,comment,creation_date,text_length,label
0,0,60202.0,364189.0,1.0,كنت اتعامل معهم اسعارهم ارخص,2024-05-11 05:56:29.327,28,Negative
1,1,60202.0,364189.0,1.0,اخر مره حصلت لي عمليه نصب على اساس الزباين غشي...,2024-05-11 05:56:29.327,245,Negative
2,2,60202.0,356203.0,1.0,عدم المصداقيه في اسعار المنتجات,2024-03-06 08:08:24.190,31,Negative
3,3,60202.0,317781.0,1.0,المتجر سئ جدا في مصداقيته في بيانات البضاعه وا...,2023-02-18 15:41:20.320,99,Negative
4,4,60202.0,285444.0,5.0,خدمه التوصيل سيئه لغايه ولا يوجد اي رد او تواص...,2022-09-03 14:01:18.933,123,Negative

In [23]:
df3 = pd.merge(df1, df[['Id', 'BusinessType']], left_on='BusinessId', right_on='Id', how='left')

# Drop the 'Id' column if you only want to keep 'BusinessId'
df3.drop('Id', axis=1, inplace=True)

In [24]:
df3.drop('Unnamed: 0', axis=1, inplace=True)

In [25]:
df3

,BusinessId,review_id,rating,comment,creation_date,text_length,label,BusinessType
0,60202.0,364189.0,1.0,كنت اتعامل معهم اسعارهم ارخص,2024-05-11 05:56:29.327,28,Negative,إلكترونيات
1,60202.0,364189.0,1.0,اخر مره حصلت لي عمليه نصب على اساس الزباين غشي...,2024-05-11 05:56:29.327,245,Negative,إلكترونيات
2,60202.0,356203.0,1.0,عدم المصداقيه في اسعار المنتجات,2024-03-06 08:08:24.190,31,Negative,إلكترونيات
3,60202.0,317781.0,1.0,المتجر سئ جدا في مصداقيته في بيانات البضاعه وا...,2023-02-18 15:41:20.320,99,Negative,إلكترونيات
4,60202.0,285444.0,5.0,خدمه التوصيل سيئه لغايه ولا يوجد اي رد او تواص...,2022-09-03 14:01:18.933,123,Negative,إلكترونيات
...,...,...,...,...,...,...,...,...
50124,44461.0,61973.0,5.0,اتعب وانا اقول انها تجن اخلاقها الحلوه وتعامله...,2018-09-16 19:00:09.143,182,Negative,خدمات الأعمال
50125,44461.0,61446.0,5.0,اكثر مايميز المتجر سرعه الرد والتوصيل السريع و...,2018-08-28 19:16:42.617,112,Positive,خدمات الأعمال
50126,44461.0,60746.0,5.0,التعامل مع متجر توليب تجربه تستحق اعادتها اكثر...,2018-07-31 02:51:11.543,150,Positive,خدمات الأعمال
50127,44461.0,60443.0,5.0,تجربتي معها جميله وانسانه ذوق واخلاق ومتعاونه ...,2018-07-22 16:43:45.897,106,Positive,خدمات الأعمال
50128,44461.0,60180.0,5.0,متجر توليب جميل جدا والتعامل اجمل,2018-07-16 08:09:20.407,33,Positive,خدمات الأعمال

In [26]:
df3['BusinessType'].value_counts()

BusinessType
خدمات الأعمال     23913
إلكترونيات         9745
الجمال والصحة      7976
أطعمة ومشروبات     2374
المنزل             1545
حفلات              1323
هدايا              1050
ازياء               757
التعليم             553
السيارات            371
منتجات رقمية        289
العقارات            164
ولاعات               69
Name: count, dtype: int64

In [27]:
Electronics =  df3[df3['BusinessType'] == 'إلكترونيات']
Business_Service =  df3[df3['BusinessType'] == 'خدمات الأعمال']
Beauty_Health=  df3[df3['BusinessType'] == 'الجمال والصحة']
Food =  df3[df3['BusinessType'] == 'أطعمة ومشروبات']
House =  df3[df3['BusinessType'] == 'المنزل']
Party=  df3[df3['BusinessType'] == 'حفلات']
Gift =  df3[df3['BusinessType'] == 'هدايا']
Clothing =  df3[df3['BusinessType'] == 'ازياء']
Education =  df3[df3['BusinessType'] == 'التعليم']
Cars =  df3[df3['BusinessType'] == 'السيارات']
Digital_Product =  df3[df3['BusinessType'] == 'منتجات رقمية']
Real_Estate =  df3[df3['BusinessType'] == 'العقارات ']
Lighters =  df3[df3['BusinessType'] == 'ولاعات']

In [29]:
Business_Service

,BusinessId,review_id,rating,comment,creation_date,text_length,label,BusinessType
8,86363.0,317047.0,1.0,تصفح سيء جدا وارسلو لي منتجات خاطئه ونموذج الا...,2023-02-09 23:35:36.383,64,Negative,خدمات الأعمال
9,86363.0,257647.0,1.0,كانو منزلين اعلان بالموقع ان العرض ينتهي اليوم...,2022-05-08 22:09:44.727,62,Negative,خدمات الأعمال
10,86363.0,257647.0,1.0,وقعد لمده اسبوعين كامله,2022-05-08 22:09:44.727,23,Negative,خدمات الأعمال
11,86363.0,257647.0,1.0,وبلغت عليهم وزاره التجاره مشكوره وحذف الاعلان ...,2022-05-08 22:09:44.727,69,Negative,خدمات الأعمال
12,86363.0,257647.0,1.0,ليش توهمون الزاير ان العرض ينتهي اليوم عشان ت...,2022-05-08 22:09:44.727,65,Negative,خدمات الأعمال
...,...,...,...,...,...,...,...,...
50124,44461.0,61973.0,5.0,اتعب وانا اقول انها تجن اخلاقها الحلوه وتعامله...,2018-09-16 19:00:09.143,182,Negative,خدمات الأعمال
50125,44461.0,61446.0,5.0,اكثر مايميز المتجر سرعه الرد والتوصيل السريع و...,2018-08-28 19:16:42.617,112,Positive,خدمات الأعمال
50126,44461.0,60746.0,5.0,التعامل مع متجر توليب تجربه تستحق اعادتها اكثر...,2018-07-31 02:51:11.543,150,Positive,خدمات الأعمال
50127,44461.0,60443.0,5.0,تجربتي معها جميله وانسانه ذوق واخلاق ومتعاونه ...,2018-07-22 16:43:45.897,106,Positive,خدمات الأعمال
50128,44461.0,60180.0,5.0,متجر توليب جميل جدا والتعامل اجمل,2018-07-16 08:09:20.407,33,Positive,خدمات الأعمال

In [ ]:
Electronics =  df3[df3['BusinessType'] == 'إلكترونيات']
Business_Service =  df3[df3['BusinessType'] == 'خدمات الأعمال']
Beauty_Health=  df3[df3['BusinessType'] == 'الجمال والصحة']
Food =  df3[df3['BusinessType'] == 'أطعمة ومشروبات']
House =  df3[df3['BusinessType'] == 'المنزل']
Party=  df3[df3['BusinessType'] == 'حفلات']
Gift =  df3[df3['BusinessType'] == 'هدايا']
Clothing =  df3[df3['BusinessType'] == 'ازياء']
Education =  df3[df3['BusinessType'] == 'التعليم']
Cars =  df3[df3['BusinessType'] == 'السيارات']
Digital_Product =  df3[df3['BusinessType'] == 'منتجات رقمية']
Real_Estate =  df3[df3['BusinessType'] == 'العقارات ']
Lighters =  df3[df3['BusinessType'] == 'ولاعات']

In [33]:
# Save each DataFrame to a CSV file
Electronics.to_csv('Electronics.csv', index=False)
Business_Service.to_csv('Business_Service.csv', index=False)
Beauty_Health.to_csv('Beauty_Health.csv', index=False)
Food.to_csv('Food.csv', index=False)
House.to_csv('House.csv', index=False)
Party.to_csv('Party.csv', index=False)
Gift.to_csv('Gift.csv', index=False)
Clothing.to_csv('Clothing.csv', index=False)
Education.to_csv('Education.csv', index=False)
Cars.to_csv('Cars.csv', index=False)
Digital_Product.to_csv('Digital_Product.csv', index=False)
Real_Estate.to_csv('Real_Estate.csv', index=False)
Lighters.to_csv('Lighters.csv', index=False)